baseURL: https://cewood.xyz/
languageCode: en-uk
title: The ramblings of cewood
theme: charaka-hugo-theme

disqusShortname: ""

copyright: "&copy; <a href=\"https://github.com/cewood\">cewood</a>"

author:
  name: blah
  homepage: blah

params:
  highlight:
    style: zenburn
  social:
    - url: "about"
      fa_icon: "fas fa-info"
    - url: "links"
      fa_icon: "fas fa-link"
    - url: "https://twitter.com/cewood"
      fa_icon: "fab fa-twitter fa-lg"
    - url: "https://github.com/cewood"
      fa_icon: "fab fa-github fa-lg"
    - url: "https://www.linkedin.com/in/cameronewood"
      fa_icon: "fab fa-linkedin-in fa-lg"
    - url: "https://stackoverflow.com/cv/cameronewood"
      fa_icon: "fab fa-stack-overflow fa-lg"

#pygmentsstyle: "zenburn"
pygmentscodefences: true
pygmentscodefencesguesssyntax: true

googleAnalytics: "UPDATEME"
